name: Run Lighthouse

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main



jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn ci
      - run: yarn build
      - name: Run Lighthouse CI
        id: lighthouse
        uses: actions/github-script@v6
        env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        with:
          script: |
              const lighthouseConfig = require('./lighthouserc');
        
              // Healthcheck
              await exec.exec('npx lhci', ['healthcheck', '--fatal']);

              // Desktop
              for await (const url of lighthouseConfig.ci.collect.url) {
                  await exec.exec('npx lhci', ['collect', '--additive', '--url', url, '--psiStrategy', 'desktop', '--settings.preset', 'desktop']);
              };

              await exec.exec('npx lhci', ['assert']);
              await exec.exec('npx lhci', ['upload', '--githubStatusContextSuffix', '/desktop']);

              // Cleanup
              await exec.exec('rm', ['-fr', '.lighthouseci']);

              // Mobile
              for await (const url of lighthouseConfig.ci.collect.url) {
                await exec.exec('npx lhci', ['collect', '--additive', '--url', url, '--psiStrategy', 'mobile']);
              };

              await exec.exec('npx lhci', ['assert']);
              await exec.exec('npx lhci', ['upload', '--githubStatusContextSuffix', '/mobile']);
        